#!/usr/bin/env node
// Build the landing page and reading pages from content files and shared templates.
// Zero dependencies. Run: `npm run build` (or `node build.mjs`).

import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { renderReadingPage } from "./src/reading-markdown.mjs";

const root = dirname(fileURLToPath(import.meta.url));
const CONTENT = join(root, "pages", "index.md");
const TEMPLATE = join(root, "src", "templates", "home.durable.html");
const STATIC_TEMPLATE = join(root, "src", "templates", "home.static.html");
const PAGE_TEMPLATE = join(root, "src", "templates", "page.html");
const STYLES = join(root, "src", "styles.css");
const OUTPUT_DIR = join(root, "docs");
const OUTPUT = join(OUTPUT_DIR, "Aster ID.dc.html");

// ── parse the `---` front-matter block of a content file ────────────────
function parseContent(src, name) {
  const m = src.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) throw new Error(`${name}: missing \`---\` front-matter block`);
  const data = {};
  for (const raw of m[1].split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const i = line.indexOf(":");
    if (i === -1) throw new Error(`${name}: no ":" in line -> ${raw}`);
    const key = line.slice(0, i).trim().toLowerCase();
    if (key in data) throw new Error(`${name}: duplicate key ${key}`);
    let val = line.slice(i + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    data[key] = val;
  }
  return data;
}

// ── placeholder filters ────────────────────────────────────────────
const escHtml = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const filters = {
  html: escHtml, // HTML text and double-quoted attributes
  attr: escHtml,
  json: (v) => JSON.stringify(v), // JS string / JSON literal, with quotes
  raw: (v) => String(v),
};

// ── run ────────────────────────────────────────────────────────────
const data = parseContent(readFileSync(CONTENT, "utf8"), "pages/index.md");
const domain = new URL(data.domain);
if (domain.protocol !== "https:" || domain.pathname !== "/" || domain.search || domain.hash) {
  throw new Error("pages/index.md: domain must be an HTTPS origin ending in /");
}
mkdirSync(OUTPUT_DIR, { recursive: true });
if (!existsSync(join(OUTPUT_DIR, "uploads"))) {
  throw new Error("docs/uploads: missing hand-managed site assets");
}

const values = {
  ...data,
  handles: (data.handles || "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean),
};

const css = readFileSync(STYLES, "utf8").trim();
const template = readFileSync(TEMPLATE, "utf8");

function render(source, locals, name) {
  const missing = new Set();
  const output = source
    .replace("%%CSS%%", () => css)
    .replace(/%%([A-Z0-9_]+)(?:\|([a-z]+))?%%/g, (whole, key, filter) => {
      const k = key.toLowerCase();
      if (!(k in locals)) {
        missing.add(key);
        return whole;
      }
      const fn = filters[filter || "html"];
      if (!fn) throw new Error(`Unknown filter "${filter}" on %%${key}%%`);
      return fn(locals[k]);
    });
  if (missing.size) throw new Error(`${name}: missing values: ${[...missing].join(", ")}`);
  return output;
}

const output = render(template, values, "src/templates/home.durable.html");

const banner = "<!DOCTYPE html>\n" + "<!-- GENERATED by build.mjs. Do not edit this file directly. -->\n";
writeFileSync(OUTPUT, output.replace(/^<!DOCTYPE html>\r?\n/, banner));

console.log("✓ wrote Aster ID.dc.html");

// Static pages reuse the header and footer from the Durable template.
const header = template.match(/<header class="site-header">[\s\S]*?<\/header>/)?.[0];
const footer = template.match(/<footer class="footer">[\s\S]*?<\/footer>/)?.[0];
if (!header || !footer) throw new Error("src/templates/home.durable.html: missing shared header or footer");
const sharedHeader = render(header, values, "header");
const sharedFooter = render(footer, values, "footer");

// Lower the chosen hero branch and the few DC bindings into static HTML.
// Keep the layout in home.durable.html so both homepage builds share it.
let main = template.match(/<main class="middle">[\s\S]*?<\/main>/)?.[0];
const structuredData = template.match(/<script type="application\/ld\+json">[\s\S]*?<\/script>/)?.[0];
if (!main || !structuredData) throw new Error("src/templates/home.durable.html: missing main or structured data");
const treatments = { balanced: "isBalanced", "handle-first": "isHandleFirst", "type-only": "isTypeOnly" };
const selected = treatments[data.hero_treatment];
if (!selected) throw new Error(`pages/index.md: unknown hero_treatment ${data.hero_treatment}`);
main = main.replace(/<sc-if\b[^>]*value="\{\{ (isBalanced|isHandleFirst|isTypeOnly) \}\}"[^>]*>([\s\S]*?)<\/sc-if>/g, (_, branch, body) =>
  branch === selected ? body : "",
);
main = main
  .replace(' onSubmit="{{ onSubmit }}" novalidate="{{ true }}"', "")
  .replace('type="email"', 'type="email" required')
  .replace(' value="{{ email }}"', "")
  .replace(' onChange="{{ onEmailChange }}"', "")
  .replace('aria-invalid="{{ invalid }}"', 'aria-invalid="false"')
  .replace("{{ error }}", "")
  .replace(' onMouseEnter="{{ pauseCycle }}" onMouseLeave="{{ resumeCycle }}"', "")
  .replace(
    'style="{{ handleStyle }}"',
    `style="width: ${Math.max(...values.handles.map((handle) => handle.length))}ch; opacity: 1; transition: opacity 600ms ease-in-out"`,
  )
  .replace("{{ handleName }}", escHtml(values.handles[0]));
if (main.includes("{{") || main.includes("<sc-if")) throw new Error("src/templates/home.durable.html: unhandled DC binding in static main");

const staticHome = render(
  readFileSync(STATIC_TEMPLATE, "utf8"),
  {
    ...values,
    header: sharedHeader,
    footer: sharedFooter,
    main: render(main, values, "main"),
    structured_data: render(structuredData, values, "structured data"),
  },
  "src/templates/home.static.html",
);
writeFileSync(join(OUTPUT_DIR, "index.html"), staticHome.replace(/^<!DOCTYPE html>\r?\n/, banner).replace(/[ \t]+$/gm, ""));
console.log("✓ wrote index.html");

const pageTemplate = readFileSync(PAGE_TEMPLATE, "utf8");
const pages = ["about", "faq", "privacy", "terms"];

for (const slug of pages) {
  const filename = `pages/${slug}.md`;
  const source = readFileSync(join(root, filename), "utf8");
  const page = parseContent(source, filename);
  if (!page.description) throw new Error(`${filename}: missing description`);
  const body = source.match(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)([\s\S]*)$/)?.[1];
  if (body === undefined) throw new Error(`${filename}: missing Markdown body after front matter`);
  const content = renderReadingPage(body.trim(), filename);
  const html = render(
    pageTemplate,
    {
      ...values,
      header: sharedHeader,
      footer: sharedFooter,
      page_title: `${content.title} — Aster ID`,
      page_description: page.description,
      page_canonical: new URL(`${slug}.html`, data.domain).href,
      page_slug: slug,
      page_placeholder: page.placeholder === "true" ? " reading-page--placeholder" : "",
      page_heading: content.heading,
      page_intro: content.intro,
      sections: content.sections,
    },
    "src/templates/page.html",
  );
  writeFileSync(join(OUTPUT_DIR, `${slug}.html`), html);
  console.log(`✓ wrote ${slug}.html`);
}

copyFileSync(join(root, "src", "support.js"), join(OUTPUT_DIR, "support.js"));
writeFileSync(join(OUTPUT_DIR, "CNAME"), `${domain.hostname}\n`);
writeFileSync(join(OUTPUT_DIR, ".nojekyll"), "");
