#!/usr/bin/env node
// Build `Aster ID.dc.html` from `template.html` + `styles.css` + copy/config in `content.md`.
// Zero dependencies. Run: `npm run build` (or `node build.mjs`).

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));
const CONTENT = join(root, "content.md");
const TEMPLATE = join(root, "template.html");
const STYLES = join(root, "styles.css");
const OUTPUT = join(root, "Aster ID.dc.html");

// ── parse the `---` front-matter block of content.md ────────────────
function parseContent(src) {
  const m = src.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) throw new Error("content.md: missing `---` front-matter block");
  const data = {};
  for (const raw of m[1].split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const i = line.indexOf(":");
    if (i === -1) throw new Error(`content.md: no ":" in line -> ${raw}`);
    const key = line.slice(0, i).trim().toLowerCase();
    let val = line.slice(i + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    data[key] = val;
  }
  return data;
}

// ── placeholder filters ────────────────────────────────────────────
const escHtml = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const filters = {
  html: escHtml, // HTML text and double-quoted attributes
  attr: escHtml,
  json: (v) => JSON.stringify(v), // JS string / JSON literal, with quotes
  raw: (v) => String(v),
};

// ── run ────────────────────────────────────────────────────────────
const data = parseContent(readFileSync(CONTENT, "utf8"));

const values = {
  ...data,
  handles: (data.handles || "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean),
};

const template = readFileSync(TEMPLATE, "utf8");
const missing = new Set();

// inline styles.css first (it contains no %%KEY%% tokens of its own)
if (!template.includes("%%CSS%%")) {
  throw new Error("template.html: missing %%CSS%% marker for styles.css");
}
const css = readFileSync(STYLES, "utf8").trim();
const styled = template.replace("%%CSS%%", () => css);

const output = styled.replace(
  /%%([A-Z0-9_]+)(?:\|([a-z]+))?%%/g,
  (whole, key, filter) => {
    const k = key.toLowerCase();
    if (!(k in values)) {
      missing.add(key);
      return whole;
    }
    const fn = filters[filter || "html"];
    if (!fn) throw new Error(`Unknown filter "${filter}" on %%${key}%%`);
    return fn(values[k]);
  }
);

if (missing.size) {
  throw new Error(
    `content.md is missing keys used by template.html: ${[...missing]
      .map((k) => k.toLowerCase())
      .join(", ")}`
  );
}

const banner =
  "<!DOCTYPE html>\n" +
  "<!-- GENERATED by build.mjs from content.md + template.html. Do not edit this file directly. -->\n";
writeFileSync(OUTPUT, output.replace(/^<!DOCTYPE html>\r?\n/, banner));

console.log("✓ wrote Aster ID.dc.html");
