#!/usr/bin/env node
// Build the landing page and reading pages from content files and shared templates.
// Zero dependencies. Run: `npm run build` (or `node build.mjs`).

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));
const CONTENT = join(root, "content.md");
const TEMPLATE = join(root, "template.html");
const PAGE_TEMPLATE = join(root, "template-page.html");
const SECTION_TEMPLATE = join(root, "template-section.html");
const STYLES = join(root, "styles.css");
const OUTPUT = join(root, "Aster ID.dc.html");

// ── parse the `---` front-matter block of a content file ────────────────
function parseContent(src, name) {
  const m = src.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) throw new Error(`${name}: missing \`---\` front-matter block`);
  const data = {};
  for (const raw of m[1].split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const i = line.indexOf(":");
    if (i === -1) throw new Error(`${name}: no ":" in line -> ${raw}`);
    const key = line.slice(0, i).trim().toLowerCase();
    if (key in data) throw new Error(`${name}: duplicate key ${key}`);
    let val = line.slice(i + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    data[key] = val;
  }
  return data;
}

// ── placeholder filters ────────────────────────────────────────────
const escHtml = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const filters = {
  html: escHtml, // HTML text and double-quoted attributes
  attr: escHtml,
  json: (v) => JSON.stringify(v), // JS string / JSON literal, with quotes
  raw: (v) => String(v),
};

// ── run ────────────────────────────────────────────────────────────
const data = parseContent(readFileSync(CONTENT, "utf8"), "content.md");

const values = {
  ...data,
  handles: (data.handles || "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean),
};

const css = readFileSync(STYLES, "utf8").trim();
const template = readFileSync(TEMPLATE, "utf8");

function render(source, locals, name) {
  const missing = new Set();
  const output = source
    .replace("%%CSS%%", () => css)
    .replace(/%%([A-Z0-9_]+)(?:\|([a-z]+))?%%/g, (whole, key, filter) => {
      const k = key.toLowerCase();
      if (!(k in locals)) {
        missing.add(key);
        return whole;
      }
      const fn = filters[filter || "html"];
      if (!fn) throw new Error(`Unknown filter "${filter}" on %%${key}%%`);
      return fn(locals[k]);
    });
  if (missing.size) throw new Error(`${name}: missing values: ${[...missing].join(", ")}`);
  return output;
}

const output = render(template, values, "template.html");

const banner = "<!DOCTYPE html>\n" + "<!-- GENERATED by build.mjs from content.md + template.html. Do not edit this file directly. -->\n";
writeFileSync(OUTPUT, output.replace(/^<!DOCTYPE html>\r?\n/, banner));
writeFileSync(join(root, "index.html"), output.replace(/^<!DOCTYPE html>\r?\n/, banner));

console.log("✓ wrote Aster ID.dc.html");
console.log("✓ wrote index.html");

// The static reading pages reuse the exact header and footer from the landing page.
const header = template.match(/<header class="site-header">[\s\S]*?<\/header>/)?.[0];
const footer = template.match(/<footer class="footer">[\s\S]*?<\/footer>/)?.[0];
if (!header || !footer) throw new Error("template.html: missing shared header or footer");
const sharedHeader = render(header, values, "header");
const sharedFooter = render(footer, values, "footer");

const pageTemplate = readFileSync(PAGE_TEMPLATE, "utf8");
const sectionTemplate = readFileSync(SECTION_TEMPLATE, "utf8");
const pages = ["about", "faq", "privacy", "terms"];

for (const [index, slug] of pages.entries()) {
  const filename = `pages/${slug}.md`;
  const page = parseContent(readFileSync(join(root, filename), "utf8"), filename);
  for (const key of ["name", "kind", "description", "lead"]) {
    if (!page[key]) throw new Error(`${filename}: missing ${key}`);
  }
  const numbers = Object.keys(page)
    .filter((key) => /^section_\d+_heading$/.test(key))
    .map((key) => Number(key.match(/\d+/)[0]))
    .sort((a, b) => a - b);
  if (!numbers.length || numbers.some((number, i) => number !== i + 1)) {
    throw new Error(`${filename}: sections must be numbered consecutively from 1`);
  }
  const sections = numbers.map((number) => {
    const prefix = `section_${number}`;
    if (!page[`${prefix}_body`]) throw new Error(`${filename}: missing ${prefix}_body`);
    const paragraphs = [page[`${prefix}_body`], page[`${prefix}_body_2`]].filter(Boolean);
    return render(
      sectionTemplate,
      {
        section_heading: page[`${prefix}_heading`],
        section_paragraphs: paragraphs.map((text) => `<p class="redacted">${escHtml(text)}</p>`).join("\n"),
      },
      "template-section.html",
    );
  });
  const html = render(
    pageTemplate,
    {
      ...values,
      header: sharedHeader,
      footer: sharedFooter,
      page_title: `${page.name} — Aster ID`,
      page_description: page.description,
      page_canonical: new URL(`${slug}.html`, data.domain).href,
      page_number: String(index + 1).padStart(2, "0"),
      page_kind: page.kind,
      page_name: page.name,
      page_lead: page.lead,
      sections: sections.join("\n"),
    },
    "template-page.html",
  );
  writeFileSync(join(root, `${slug}.html`), html);
  console.log(`✓ wrote ${slug}.html`);
}
